# Generated by Django 3.1.4 on 2020-12-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201222_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='header',
            field=models.CharField(default=111111, max_length=20),
            preserve_default=False,
        ),
    ]
