# Generated by Django 3.1.4 on 2020-12-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_detail_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='header',
        ),
    ]
