# Generated by Django 3.1.4 on 2020-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_detail_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='header',
            field=models.CharField(default='Page details', max_length=20),
        ),
    ]
