# Generated by Django 3.1.4 on 2020-12-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_detail_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='home_care_paragraph',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='detail',
            name='home_comm_paragraph',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='detail',
            name='home_ontime_paragraph',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='detail',
            name='vision_paragraph',
            field=models.TextField(max_length=400),
        ),
    ]
