# Generated by Django 3.1.4 on 2020-12-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('inclusion_one', models.CharField(max_length=100)),
                ('inclusion_two', models.CharField(max_length=100)),
                ('inclusion_three', models.CharField(max_length=100)),
                ('inclusion_four', models.CharField(max_length=100)),
                ('inclusion_five', models.CharField(max_length=100)),
                ('inclusion_six', models.CharField(max_length=100)),
                ('inclusion_seven', models.CharField(max_length=100)),
                ('inclusion_eight', models.CharField(max_length=100)),
            ],
        ),
    ]
