# Generated by Django 3.1.4 on 2020-12-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='inclusion_eight',
        ),
        migrations.RemoveField(
            model_name='service',
            name='inclusion_five',
        ),
        migrations.RemoveField(
            model_name='service',
            name='inclusion_seven',
        ),
        migrations.RemoveField(
            model_name='service',
            name='inclusion_six',
        ),
    ]
